#!/usr/bin/env node
/**
 * compile-content.mjs
 *
 * Reads config/raw/*.json, validates each against its Zod schema, and emits
 * config/compiled/content.ts (gitignored). Wired into predev / prebuild /
 * pretypecheck / pretest so the compiled module is always present when
 * TypeScript or Vite runs.
 *
 * Full implementation lands in PR G. This PR A stub emits a minimal module
 * so pre-hooks and imports do not fail while the sim layer is built.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const here = path.dirname(fileURLToPath(import.meta.url));
const outDir = path.resolve(here, '..', 'config', 'compiled');
const outFile = path.join(outDir, 'content.ts');

mkdirSync(outDir, { recursive: true });

const header = `// Auto-generated by scripts/compile-content.mjs — do not edit.\n// Populated in PR G.\n\n`;
const body = `export const content = {\n  progression: null,\n  patterns: null,\n  shapes: null,\n  sessionModes: null,\n  codenameWords: null,\n  opponentTuning: null,\n} as const;\n\nexport type Content = typeof content;\n`;

writeFileSync(outFile, header + body, 'utf8');
process.stdout.write(`compile-content → ${path.relative(process.cwd(), outFile)}\n`);
